{{- range $configName, $configContent := .Values.acme }}
{{- if $configContent.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $configName }}
spec:
  acme:
    server: {{ $configContent.acmeServer }}
    privateKeySecretRef:
      name: {{ $configName }}-key
    solvers: {{ toYaml $configContent.solvers | nindent 6 }}
{{- end }}
{{- end }}
