apiVersion: v1
kind: Service
metadata:
  name: {{ default $.Release.Name $.Values.nameOverride }}-api-svc
spec:
  selector:
    app: {{ default $.Release.Name $.Values.nameOverride }}
    service: api-server
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  type: ClusterIP
