apiVersion: v1
kind: Service
metadata:
 name: traefik-nodeport
 namespace: kube-system
spec:
 type: NodePort
 selector:
  app.kubernetes.io/name: traefik
 ports:
 - name: web
   port: 80
   targetPort: 8000
   nodePort: 31080
