{{- range $configName, $configContent := .Values.configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $configName }}
data: {{ tpl (toYaml $configContent) $ | nindent 4 }}
{{- end }}
