# values.auth-basic.yaml
configMap:
  auth:
    # Follow this guide for information on obtaining these values from Google
    # https://docs.onyx.app/google_oauth_setup
    AUTH_TYPE: google_oauth
    GOOGLE_OAUTH_CLIENT_ID: '#USER_SUPPLIED#'
    GOOGLE_OAUTH_CLIENT_SECRET: '#USER_SUPPLIED'

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
  tls: true
  hostname: "onyx.#USER_SUPPLIED#"

inference:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/device-plugin.config
              operator: In
              values:
                - tesla-25b6
                - tesla-2235
                - tesla-27b8
                - tesla-26b9

index:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/device-plugin.config
              operator: In
              values:
                - tesla-25b6
                - tesla-2235
                - tesla-27b8
                - tesla-26b9

