# values.ha.yaml
# This section is necessary to inform Onyx how to connect to both the vespa-ai configuration statefulSet and the vespa-ai content statefulSet
configMap:
  vespa:
    VESPA_CONFIG_SERVER_HOST: 'vespa-cfg'
    VESPA_HOST: 'vespa-content'
vespa:
  statefulSets:
    # Disabling the default single-replica statefulSet
    single: { enabled: false }
    cfg:
      enabled: true
      replicaCount: 3
    content:
      enabled: true
      replicaCount: 3
# Use the hotpatch system to override the number of replica copies of data to be stored in the vespa database
hotpatch:
  vespaRedundancy: 2
web:
  replicaCount: 2
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
  tls: true
  hostname: "onyx.#USER_SUPPLIED_ROOT_DOMAIN#"
# Only launch the inference and index model pods on GPU VMs
inference:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/device-plugin.config
              operator: In
              values:
                - tesla-25b6
                - tesla-2235
                - tesla-27b8
                - tesla-26b9

index:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/device-plugin.config
              operator: In
              values:
                - tesla-25b6
                - tesla-2235
                - tesla-27b8
                - tesla-26b9

