# values.aws-load-balancer-controller.yaml
clusterName: #USER_SUPPLIED_CLUSTER_NAME#
controllerConfig:
  featureGates:
    ALBSingleSubnet: true
    SubnetsClusterTagCheck: false
ingressClassConfig:
  default: true
enableShield: false
enableWaf: false
enableWafv2: false
awsApiEndpoints: "ec2={{ .Values.endpointUrl }}/api/v2/aws/ec2,elasticloadbalancing={{ .Values.endpointUrl }}/api/v2/aws/elbv2,acm={{ .Values.endpointUrl }}/api/v2/aws/acm,sts={{ .Values.endpointUrl }}/api/v2/aws/sts"
tolerations:
  - key: ""
    effect: NoSchedule
    operator: Exists
  - key: ""
    effect: NoExecute
    operator: Exists
