# values.aws-load-balancer-controller.yaml
clusterName: #USER_SUPPLIED_CLUSTER_NAME#
controllerConfig:
  featureGates:
    ALBSingleSubnet: true
    SubnetsClusterTagCheck: false
ingressClassConfig:
  default: true
enableShield: false
enableWaf: false
enableWafv2: false
awsApiEndpoints: "ec2={{ tpl $.Values.serviceOverrides.ec2.Url $ }},elasticloadbalancing={{ tpl $.Values.serviceOverrides.elasticloadbalancing.Url $ }},acm={{ tpl $.Values.serviceOverrides.acm.Url $ }},sts={{ tpl $.Values.serviceOverrides.sts.Url $ }}"
tolerations:
  - key: ""
    effect: NoSchedule
    operator: Exists
  - key: ""
    effect: NoExecute
    operator: Exists
